name: Transifex

on:
  # Triggers the workflow on push events only for the master branch
  push:
    branches: [ master ]

env:
  TRANSIFEX_API_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
      - name: Run script to push English strings to Transifex
        run: |
          chmod +x ./scripts/push-to-transifex.sh
          ./scripts/push-to-transifex.sh
        shell: bash